# Generated by Django 5.1.3 on 2024-12-04 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
