# Generated by Django 5.2.4 on 2025-08-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('order_cancel', 'Can cancel an order')]},
        ),
    ]
